import { Home, Wallet, Package, History, Download, Phone, Newspaper, Code2 } from "lucide-react";

export const NAV_MAIN = [
  { key: "home", label: "Trang chủ", icon: Home, path: "/" },
  { key: "topup", label: "Nạp tiền", icon: Wallet, badge: "Auto", path: "/nap-tien" },
  { key: "orders", label: "Đơn hàng", icon: Package, path: "/don-hang" },
  { key: "history", label: "Lịch sử giao dịch", icon: History, path: "/lich-su-giao-dich" },
];

export const NAV_SERVICE = [
  { key: "news", label: "Tin tức & Blog", icon: Newspaper, path: "/tin-tuc" },
  { key: "download", label: "Tải xuống", icon: Download, badge: "Free", path: "/tai-xuong" },
  { key: "api", label: "API Seller", icon: Code2, path: "/api-seller" },
  { key: "contact", label: "Liên hệ", icon: Phone, path: "/lien-he" },
];

export const NOTIFICATIONS = [
  {
    id: 1,
    title: "Nạp tiền thành công",
    detail: "Số dư của bạn vừa được cộng thêm 200.000đ.",
    time: "2 phút trước",
    tone: "success",
  },
  {
    id: 2,
    title: "Đơn hàng đã hoàn tất",
    detail: "Đơn #GS-10432 đã được giao thành công.",
    time: "1 giờ trước",
    tone: "success",
  },
  {
    id: 3,
    title: "Sản phẩm mới được cập nhật",
    detail: 'Gói "Performance Booster Pro" vừa ra bản v3.2.',
    time: "Hôm qua",
    tone: "info",
  },
];

export const FEEDBACKS = [
  { id: 1, name: "Minh Khang", text: "Giao dịch nhanh, hỗ trợ nhiệt tình, sẽ ủng hộ lâu dài.", stars: 5 },
  { id: 2, name: "Thảo Uyên", text: "Sản phẩm đúng như mô tả, kích hoạt trong vài phút.", stars: 5 },
  { id: 3, name: "Quốc Bảo", text: "Giá hợp lý, key hoạt động ổn định suốt thời gian dùng.", stars: 4 },
  { id: 4, name: "Hải Đăng", text: "Đội ngũ CSKH phản hồi cực nhanh, rất chuyên nghiệp.", stars: 5 },
];

export const CATEGORIES = [
  { key: "all", label: "Tất cả" },
  { key: "perf", label: "TỐI ƯU HIỆU NĂNG" },
  { key: "config", label: "CẤU HÌNH GAME" },
  { key: "license", label: "BẢN QUYỀN PHẦN MỀM" },
  { key: "service", label: "GÓI DỊCH VỤ" },
];

export const PRODUCTS = [
  {
    id: 1,
    name: "Performance Booster Pro",
    category: "perf",
    categoryLabel: "Tối ưu hiệu năng",
    desc: "Tối ưu tài nguyên hệ thống, tăng FPS ổn định cho máy cấu hình thấp.",
    features: ["Giảm độ trễ hệ thống", "Tối ưu RAM & CPU", "Tương thích đa nền tảng"],
    stock: 81,
    pack: 1,
    sold: 281,
    price: "350.000đ",
    status: "in",
  },
  {
    id: 2,
    name: "Game Config Optimizer",
    category: "config",
    categoryLabel: "Cấu hình game",
    desc: "Bộ cấu hình sẵn giúp game khởi động nhanh và mượt hơn.",
    features: ["Cấu hình đồ họa tối ưu", "Tự động backup setting", "Hỗ trợ nhiều tựa game"],
    stock: 46,
    pack: 1,
    sold: 194,
    price: "220.000đ",
    status: "in",
  },
  {
    id: 3,
    name: "Software License Key",
    category: "license",
    categoryLabel: "Bản quyền phần mềm",
    desc: "Key bản quyền chính hãng, kích hoạt trọn đời cho thiết bị.",
    features: ["Bản quyền chính hãng", "Kích hoạt trọn đời", "Hỗ trợ cập nhật miễn phí"],
    stock: 0,
    pack: 1,
    sold: 512,
    price: "450.000đ",
    status: "out",
  },
  {
    id: 4,
    name: "Cloud Backup Plan",
    category: "service",
    categoryLabel: "Gói dịch vụ",
    desc: "Dịch vụ sao lưu đám mây bảo mật cho dữ liệu cá nhân.",
    features: ["Dung lượng 100GB", "Mã hoá đầu cuối", "Đồng bộ đa thiết bị"],
    stock: 120,
    pack: 3,
    sold: 98,
    price: "150.000đ",
    status: "in",
  },
  {
    id: 5,
    name: "System Optimizer Suite",
    category: "perf",
    categoryLabel: "Tối ưu hiệu năng",
    desc: "Bộ công cụ dọn dẹp và tăng tốc hệ thống toàn diện.",
    features: ["Dọn rác hệ thống", "Tăng tốc khởi động", "Giám sát hiệu năng realtime"],
    stock: 63,
    pack: 1,
    sold: 176,
    price: "180.000đ",
    status: "in",
  },
  {
    id: 6,
    name: "Pro Config Bundle",
    category: "config",
    categoryLabel: "Cấu hình game",
    desc: "Combo cấu hình chuyên sâu dành cho nhiều thể loại game.",
    features: ["10+ cấu hình dựng sẵn", "Cập nhật định kỳ", "Hướng dẫn chi tiết"],
    stock: 27,
    pack: 2,
    sold: 87,
    price: "290.000đ",
    status: "in",
  },
  {
    id: 7,
    name: "Streaming Access Pass",
    category: "service",
    categoryLabel: "Gói dịch vụ",
    desc: "Gói truy cập dịch vụ giải trí trực tuyến thời hạn 1 tháng.",
    features: ["Xem không giới hạn", "Chất lượng Full HD", "Dùng trên nhiều thiết bị"],
    stock: 200,
    pack: 1,
    sold: 342,
    price: "99.000đ",
    status: "in",
  },
  {
    id: 8,
    name: "Creative Software License",
    category: "license",
    categoryLabel: "Bản quyền phần mềm",
    desc: "Bản quyền phần mềm sáng tạo nội dung, sử dụng chính chủ.",
    features: ["Kích hoạt chính chủ", "Không giới hạn thiết bị chính", "Hỗ trợ kỹ thuật 24/7"],
    stock: 15,
    pack: 1,
    sold: 63,
    price: "520.000đ",
    status: "in",
  },
  {
    id: 9,
    name: "Network Optimizer Key",
    category: "perf",
    categoryLabel: "Tối ưu hiệu năng",
    desc: "Tối ưu đường truyền mạng, giảm ping khi chơi game online.",
    features: ["Giảm ping trung bình 20%", "Ổn định kết nối", "Cấu hình theo khu vực"],
    stock: 54,
    pack: 1,
    sold: 231,
    price: "160.000đ",
    status: "in",
  },
];

/* ---------- Orders (demo) ---------- */
export const ORDERS = [
  {
    id: "ORD-MS05QHF21A",
    productName: "System Optimizer Suite",
    packageName: "GÓI 7 NGÀY",
    status: "success", // success | processing | cancelled | expired
    amount: 90000,
    purchasedAt: "21:49:15 11/8/2026",
    completedAt: "21:49:32 11/8/2026",
    adminNote:
      "Sau khi kích hoạt, khởi động lại ứng dụng để áp dụng cấu hình tối ưu. Liên hệ hỗ trợ nếu key báo lỗi.",
    productKey: "SOS7day1rnLbcGg5Jk",
    expiresInSeconds: 19774, // ~5h 29m 34s
    supportsHwidReset: true,
  },
  {
    id: "ORD-7YQ2KX90PL",
    productName: "Performance Booster Pro",
    packageName: "GÓI VĨNH VIỄN",
    status: "success",
    amount: 350000,
    purchasedAt: "10:12:04 9/8/2026",
    completedAt: "10:12:19 9/8/2026",
    adminNote: "Bản quyền vĩnh viễn, không cần gia hạn. Xem hướng dẫn kích hoạt trong mục Tải xuống.",
    productKey: "PBP-LT-88213-QXHV",
    expiresInSeconds: null,
    supportsHwidReset: true,
  },
  {
    id: "ORD-3F8DNC12ZT",
    productName: "Cloud Backup Plan",
    packageName: "GÓI 30 NGÀY",
    status: "processing",
    amount: 150000,
    purchasedAt: "08:41:50 12/8/2026",
    completedAt: null,
    adminNote: "Đơn hàng đang được xử lý, key sẽ được gửi trong vòng vài phút.",
    productKey: null,
    expiresInSeconds: null,
    supportsHwidReset: false,
  },
  {
    id: "ORD-9K1LWE44RS",
    productName: "Software License Key",
    packageName: "GÓI 1 NĂM",
    status: "expired",
    amount: 450000,
    purchasedAt: "02:15:00 20/7/2026",
    completedAt: "02:15:40 20/7/2026",
    adminNote: "Key đã hết hạn sử dụng. Vui lòng mua gói mới để tiếp tục sử dụng dịch vụ.",
    productKey: "SLK-EXP-10293-OLD",
    expiresInSeconds: 0,
    supportsHwidReset: false,
  },
  {
    id: "ORD-5H2QVB77YM",
    productName: "Streaming Access Pass",
    packageName: "GÓI 1 THÁNG",
    status: "cancelled",
    amount: 99000,
    purchasedAt: "19:03:11 5/8/2026",
    completedAt: null,
    adminNote: "Đơn hàng đã bị hủy do thanh toán không hợp lệ. Số dư đã được hoàn lại.",
    productKey: null,
    expiresInSeconds: null,
    supportsHwidReset: false,
  },
];

/* ---------- Transaction history (demo) ---------- */
export const TRANSACTIONS = [
  {
    id: "TX-0091",
    type: "purchase", // purchase | topup | refund
    title: "System Optimizer Suite",
    subtitle: "GÓI 7 NGÀY",
    time: "21:49:15 11/8/2026",
    amount: -90000,
    balanceAfter: 0,
  },
  {
    id: "TX-0090",
    type: "topup",
    title: "Nạp QR",
    subtitle: "Ngân hàng • Chuyển khoản",
    time: "21:48:23 11/8/2026",
    amount: 90000,
    balanceAfter: 90000,
  },
  {
    id: "TX-0089",
    type: "purchase",
    title: "Cloud Backup Plan",
    subtitle: "GÓI 30 NGÀY",
    time: "08:41:50 12/8/2026",
    amount: -150000,
    balanceAfter: 200000,
  },
  {
    id: "TX-0088",
    type: "refund",
    title: "Hoàn tiền — Streaming Access Pass",
    subtitle: "Đơn hàng bị hủy",
    time: "19:05:02 5/8/2026",
    amount: 99000,
    balanceAfter: 350000,
  },
  {
    id: "TX-0087",
    type: "topup",
    title: "Nạp QR",
    subtitle: "Ngân hàng • Chuyển khoản",
    time: "09:20:11 5/8/2026",
    amount: 200000,
    balanceAfter: 251000,
  },
  {
    id: "TX-0086",
    type: "purchase",
    title: "Performance Booster Pro",
    subtitle: "GÓI VĨNH VIỄN",
    time: "10:12:04 9/8/2026",
    amount: -350000,
    balanceAfter: 51000,
  },
];

/* ---------- Downloads (demo, generic/legitimate categories only) ---------- */
export const DOWNLOAD_CATEGORIES = [
  { key: "all", label: "Tất cả" },
  { key: "launcher", label: "LAUNCHER & CÔNG CỤ" },
  { key: "emulator", label: "GIẢ LẬP" },
  { key: "drivers", label: "DRIVERS" },
  { key: "virtualization", label: "ẢO HÓA HỆ THỐNG" },
  { key: "recording", label: "GHI HÌNH & STREAM" },
];

export const DOWNLOADS = [
  {
    id: 1,
    name: "GearStore_Launcher_v3.2.1.exe",
    category: "launcher",
    categoryLabel: "Launcher & công cụ",
    desc: "Ứng dụng khởi chạy chính thức, tự động cập nhật và quản lý license.",
    downloads: "12.4k",
    size: "48 MB",
    hasVideo: true,
    hasGuide: true,
  },
  {
    id: 2,
    name: "Emulator_Pro_Setup_5.0.exe",
    category: "emulator",
    categoryLabel: "Giả lập",
    desc: "Bộ giả lập hiệu năng cao, hỗ trợ đa nhân ảo và cấu hình tuỳ chỉnh.",
    downloads: "8.1k",
    size: "1.2 GB",
    hasVideo: true,
    hasGuide: true,
  },
  {
    id: 3,
    name: "GPU_Driver_Universal_552.44.exe",
    category: "drivers",
    categoryLabel: "Drivers",
    desc: "Driver đồ họa tổng hợp, tương thích nhiều dòng card phổ biến.",
    downloads: "22.7k",
    size: "620 MB",
    hasVideo: false,
    hasGuide: true,
  },
  {
    id: 4,
    name: "Virtualization_Toggle_Tool.exe",
    category: "virtualization",
    categoryLabel: "Ảo hóa hệ thống",
    desc: "Công cụ bật/tắt tính năng ảo hóa hệ thống phục vụ chạy giả lập.",
    downloads: "5.5k",
    size: "3 MB",
    hasVideo: false,
    hasGuide: true,
  },
  {
    id: 5,
    name: "Stream_Record_FixPack.zip",
    category: "recording",
    categoryLabel: "Ghi hình & stream",
    desc: "Gói khắc phục lỗi ghi hình/stream phổ biến trên phần mềm capture.",
    downloads: "3.9k",
    size: "210 MB",
    hasVideo: true,
    hasGuide: false,
  },
  {
    id: 6,
    name: "Emulator_Lite_Setup_5.0.exe",
    category: "emulator",
    categoryLabel: "Giả lập",
    desc: "Phiên bản nhẹ của bộ giả lập, tối ưu cho máy cấu hình thấp.",
    downloads: "6.6k",
    size: "780 MB",
    hasVideo: false,
    hasGuide: true,
  },
  {
    id: 7,
    name: "Network_Driver_Pack.exe",
    category: "drivers",
    categoryLabel: "Drivers",
    desc: "Bộ driver mạng hỗ trợ ổn định kết nối cho nhiều dòng thiết bị.",
    downloads: "4.2k",
    size: "95 MB",
    hasVideo: false,
    hasGuide: false,
  },
  {
    id: 8,
    name: "GearStore_Launcher_Beta.exe",
    category: "launcher",
    categoryLabel: "Launcher & công cụ",
    desc: "Bản beta của launcher, thử nghiệm tính năng mới trước khi phát hành chính thức.",
    downloads: "1.3k",
    size: "51 MB",
    hasVideo: false,
    hasGuide: true,
  },
];

/* ---------- Contact channels (demo) ---------- */
export const CONTACT_CHANNELS = [
  {
    id: 1,
    name: "Zalo Cá Nhân",
    desc: "Nhắn tin trực tiếp để được hỗ trợ 1-1 nhanh nhất",
    badges: ["Cá nhân", "Phản hồi nhanh"],
    iconKey: "zalo",
    url: "https://zalo.me/",
  },
  {
    id: 2,
    name: "Zalo Nhóm Cộng Đồng 1",
    desc: "Tham gia nhóm để trao đổi, hỏi đáp cùng cộng đồng người dùng",
    badges: ["Nhóm", "Cộng đồng"],
    iconKey: "zalo",
    url: "https://zalo.me/",
  },
  {
    id: 3,
    name: "Zalo Nhóm Cộng Đồng 2",
    desc: "Nhóm dự phòng khi nhóm chính đã đầy thành viên",
    badges: ["Nhóm", "Cộng đồng"],
    iconKey: "zalo",
    url: "https://zalo.me/",
  },
  {
    id: 4,
    name: "Facebook Cá Nhân",
    desc: "Kết bạn và nhắn tin trực tiếp qua Messenger",
    badges: ["Cá nhân", "Phản hồi nhanh"],
    iconKey: "facebook",
    url: "https://facebook.com/",
  },
  {
    id: 5,
    name: "Facebook Group",
    desc: "Cộng đồng người dùng chia sẻ kinh nghiệm và cập nhật mới",
    badges: ["Cộng đồng"],
    iconKey: "facebook",
    url: "https://facebook.com/",
  },
];
